name: Hexo Deploy

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: source

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo Dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: Setup aurora Theme Dependencies
        run: |
          cd ./themes/aurora
          npm install

      - name: Setup Deploy Private Key
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Setup Git Information
        run: |
          git config --global user.email "imwuxi@gmail.com"
          git config --global user.name "liwuxi"
          
      - name: Deploy
        run: |
          hexo clean
          hexo generate
          hexo deploy
